### ISSUE TITLE
Creating or updating records where there is a unique field clash causes a raw error message to be displayed in the front end

### ISSUE THREAD

**Issue by unknowndomain** [creativetechnologylab/checkout#18]
> Error - error: update "items" set "name" = $1, "barcode" = $2, "label" = $3, "location_id" = $4, "value" = $5, "notes" = $6, "group_id" = $7 where "items"."id" = $8 - duplicate key value violates unique constraint "items_barcode_unique"

**Comment by unknowndomain** [comment]
This happens in all cases where there is a unique field

**Comment by jthawme** [comment]
2 things. The error is an odd one from postgres, it is after a mass import, it doesnt fix. Created issue to maybe fix this #21

Displaying the raw error is on purpose, but after we have logging I will change this #22
